# Generated by Django 4.2.23 on 2025-08-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('land_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='static/img/farmers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
