# Generated by Django 4.2.20 on 2026-03-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0002_otpstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffattendance',
            name='date',
            field=models.DateField(),
        ),
    ]
