# Generated by Django 4.2.20 on 2025-08-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('mobile_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('job_role', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='employee_photos/')),
            ],
        ),
    ]
