# Generated by Django 4.2.20 on 2025-08-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0006_contactmessage_delete_adminuser_delete_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
