# Generated by Django 4.2.20 on 2025-08-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
    ]
