# Generated by Django 4.2.20 on 2025-08-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0011_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='crop_name',
            field=models.CharField(default='Unnamed Crop', max_length=100),
            preserve_default=False,
        ),
    ]
