# Generated by Django 4.2.20 on 2025-08-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0013_attendance_driver_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
