# Generated by Django 4.2.20 on 2025-08-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0014_delete_attendance_delete_driver_delete_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('license_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='driver_photos/')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
