# Generated by Django 4.2.20 on 2025-08-22 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0017_staffattendance_driverattendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StaffAttendance',
        ),
    ]
