# Generated by Django 4.2.20 on 2025-08-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0019_staffattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driverattendance',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='driverattendance',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='driverattendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10),
        ),
    ]
