# Generated by Django 4.2.20 on 2025-08-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0020_alter_driverattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_id', models.CharField(max_length=50, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_company', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('vehicle_img', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
            ],
        ),
    ]
