# Generated by Django 4.2.20 on 2025-08-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0022_vehicle_id_alter_vehicle_vehicle_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='id',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
