# Generated by Django 4.2.20 on 2025-08-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0023_remove_vehicle_id_alter_vehicle_vehicle_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
