# Generated by Django 4.2.20 on 2025-08-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0025_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='customer',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer_email',
            field=models.EmailField(default='unknown', max_length=254),
            preserve_default=False,
        ),
    ]
