# Generated by Django 4.2.20 on 2025-08-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzhavankart', '0027_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='order',
            name='crop_name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
